package com.ai.project.entity.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_PASSWORD_CHANGED,
    ADMIN_USER_DEACTIVATED,
    CREDENTIAL_ADDED,
    CREDENTIAL_DELETED,
    DEPLOYMENT_GENERATED,
    DEPLOYMENT_APPROVED,
    DEPLOYMENT_REJECTED,
    DEPLOYMENT_EXECUTING,
    DEPLOYMENT_SUCCESS,
    DEPLOYMENT_FAILED,
    DEPLOYMENT_DESTROY_INITIATED,
    DEPLOYMENT_DESTROYED,
    DEPLOYMENT_DESTROY_FAILED,
    PROMPT_POLICY_VIOLATION
}